apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: main-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - image: tabletopltd/tt-main
        name: main
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://localhost:32696
        ports:
        - containerPort: 8090
          name: server
          protocol: TCP
